### ISSUE TITLE
Is Leaflet loading vue.esm twice?

### ISSUE THREAD

**Issue by gkatsanos** [KoRiGaN/Vue2Leaflet#100]
I did a bundle analysis and I see that vue2-leaflet loads vue.esm.js separately for some reason?

![image](https://user-images.githubusercontent.com/1768834/32995798-04c71840-cd7a-11e7-9015-f8cd275125aa.png)

**Comment by valscion** [comment]
It might be that `vue2-leaflet` should declare `vue` in `peerDependencies` (and possibly `devDependencies` for developing the package itself) to avoid this situation. A similar issue over at React ecosystem has been fixed with a similar solution, e.g. here: https://github.com/JedWatson/react-select/pull/116

**Comment by KoRiGaN** [comment]
Hi @gkatsanos,

I agree with @valscion.

I will try to fix this.

Micka

**Comment by KoRiGaN** [comment]
Hi @gkatsanos  @valscion,
This should now be fixed in v0.0.58.

Let me know if it works for you.

Micka

**Comment by KoRiGaN** [comment]
Closing as no answer for a while.

**Comment by gkatsanos** [comment]
Sorry, my project in question was abandoned, but in case this comes up again I'll make a new issue. Thanks for handling!
