### ISSUE TITLE
No "zoomControl" support in Map element

### ISSUE THREAD

**Issue by vladimarius** [KoRiGaN/Vue2Leaflet#125]
Hi,

Doc states that Vue2Leaflet supports Map element. However i cannot find no prop for "zoomControl". Is that a bug or a feature ?

**Comment by rnvitter** [comment]
try this
`<v-map id="twitter-map" ref="map" :zoom="zoom" :center="center" :options="{ zoomControl: false }">` @vladimarius

**Comment by KoRiGaN** [comment]
Hi @vladimarius,

It's a feature. Zoom as well as Attribution, Scale and Layer control are Controls in Leaflet and they are not yet implemented in Vue2Leaflet.

I would like to see them implemented but because of lack of time they are not yet.
There is a PR for Layer control so I think will implement the other ones when merging this PR.

Leaflet Map give some options to change its controls like zoomControl and attribution so these options are also available in Vue2Leaflet.

Hope this helps

Micka

**Comment by KoRiGaN** [comment]
Hi @vladimarius, @rnvitter,

Zoom Control is now implemented in Vue2Leaflet v1.0.1
 
Let me know if it solves your issue.

Micka

**Comment by KoRiGaN** [comment]
Closing as no comments for 3 weeks.
Please reopen this issue if it not solved yet.
