### ISSUE TITLE
src of tilelayer is not right

### ISSUE THREAD

**Issue by hosein2398** [KoRiGaN/Vue2Leaflet#134]
### Description
`tilelayer` is not shown.  

Firstly, there is no note is docs that we should copy `images` folder (or at least `marker-icon.png`) into our project's static folder, that would be better if you notice this in doc. 

Second, `tilelayer` is not shown for me, because the `src` attribute that you are generating for that image is reffrering to `/images/marker-icon.png` and instead, as of[ this page](http://vuejs-templates.github.io/webpack/static.html) it should should be  `static/images/marker-icon.png`.  

I know it's fine and working in your examples folder, but I don't why it's broken in mines, maybe that's because of vue webpack template update.

### Versions
- Leaflet: !! not installed
- Vue: 2.5.2
- Vue2Leaflet: 0.0.58

**Comment by KoRiGaN** [comment]
Hi @hosein2398,

First, you seem to have a problem with markers. This problem is well known and you should look at issue #28 and #96. Webpack and Leaflet don't work well together.
Icon paths are generated by leaflet, not by vue2leaflet.
There is no need to copy marker-icons, webpack should do it. I copy them in my example folder only to demonstrate that you can use Leaflet default imagePath to customize icons for example. 

Second, you are mixing tilelayer and markers. 
- If you have an issue with marker look at the issues mentioned above,
- If you have issues with the tilelayer (background layers) please explain how to reproduce.

Hope this helps,

Mickaël

**Comment by hosein2398** [comment]
Hi,
Yeah sorry, it's marker,
Changing imagePath to this:
`L.Icon.Default.imagePath = "static/images/"`
seems handy for mine.

In my project it does not work if I don't copy images into my static, even though i don't want to use custom icons.

Thanks

**Comment by KoRiGaN** [comment]
Please read issue #96.

The recommendation is to use :
```
import L from 'leaflet';
delete L.Icon.Default.prototype._getIconUrl;

L.Icon.Default.mergeOptions({
  iconRetinaUrl: require('leaflet/dist/images/marker-icon-2x.png'),
  iconUrl: require('leaflet/dist/images/marker-icon.png'),
  shadowUrl: require('leaflet/dist/images/marker-shadow.png')
});
```

**Comment by hosein2398** [comment]
Yup that's it. it works with that.
And as I understood to load any kinda custom icon we should put icon into `L.Icon.Default.imagePath` path.
Thanks
