### ISSUE TITLE
heatmap-leaflet + Vue2Leaflet

### ISSUE THREAD

**Issue by nik-el** [KoRiGaN/Vue2Leaflet#199]
Hello!
Thanks for excellent Vue2Leaflet.

Can somebody create example how integrate [heatmap-leaflet](https://www.patrick-wied.at/static/heatmapjs/plugin-leaflet-layer.html) with Vue2Leaflet?

**Comment by jurb** [comment]
@nik-el I had a go at it, see [vue2-leaflet-heatmap](https://github.com/jurb/vue2-leaflet-heatmap). I used [Leaflet.heat](https://github.com/Leaflet/Leaflet.heat). I can't get it working via npm yet, but you can just copy the .vue file from the repository.

@jperelli since you already implemented markercluster, would you happen to now what goes wrong with the npm part? I made an issue about it here: https://github.com/jurb/vue2-leaflet-heatmap/issues/1.

**Comment by jurb** [comment]
@lordfuoco That would be amazing! I think (hope) I'm pretty close, but I don't know how to proceed. If you have any idea about how to go about solving [this issue](https://github.com/jurb/vue2-leaflet-heatmap/issues/1) I'm all ears!

**Comment by lordfuoco** [comment]
@jurb when you are ready with your plugin feel free to make a PR to add it to the readme! Closing here
