### ISSUE TITLE
Reactivity issue with l-marker options prop

### ISSUE THREAD

**Issue by Carnid** [KoRiGaN/Vue2Leaflet#245]
### Description

Maybe I don't understand how Vue2Leaflet wraps the leaflet library, but some expected practices don't seem to work properly with some features. Notably, the `options` prop, wherever it exists, doesn't seem to allow for reactivity. I can set an initial value to options, but whenever I try to bind it to a changing property, the changes don't seem to be applied to the related object. I have given a fiddle with an example for l-marker and the `interactive` option.

#### Live Demo

http://jsfiddle.net/0snpjgbe/

#### Steps to Reproduce
See fiddle.

#### Expected Results

When the option object given as prop changes, it should be applied. (In the given fiddle, when toggling Interactivity, the markers should not be interactive anymore)

#### Actual Results

The pins stay interactive.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: v1.3.2
- Vue: v2.5.3
- Vue2Leaflet: v1.0.2

**Comment by lordfuoco** [comment]
@Carnid reactivity works on the properties which have a matching set / getter function in leaflet, so that we can update the property without having to redraw the whole element ( or chain of elements )
in this case the interactive options come from interactive layer and interactive layer does not have a setInteractivity method to update the property 'on the go' , but maybe you use case has a point and we should add a method to interactive layer to address this.

I will think of a change in this sense but is going to be done on the next branch, you can install it with: 
"vue2-leaflet": "git+https://github.com/KoRiGaN/Vue2Leaflet.git#next",

**Comment by lordfuoco** [comment]
@Carnid any contribution is welcomed, feel free to fork and checkout the master branch, at the end of the readme you will find the contribution guide.

The master branch is quite active since we are working on some bugfixes after a major refactor but we are happy for another set of hands!

**Comment by DonNicoJs** [comment]
@Carnid are you still interested in working on this? Closing for now but feel free to re-open
