### ISSUE TITLE
marker isn't reactive after updating vue2-leaflet

### ISSUE THREAD

**Issue by jkatagi** [KoRiGaN/Vue2Leaflet#274]
### Description
I updated vue2-leaflet from v1.0.2 to v1.1.1 but after updating, marker isn't reactive.

I manage the marker's latlng in stores to update it from other components (e.x. from Exif information of pictures), so the code is a little complicated.

Could you tell me what happened? thanks.

#### Live Demo
- works at v1.02 : [jsfiddle](https://jsfiddle.net/futr8xv7/2/)
- doesn't work at v1.1.1 : [jsfiddle](https://jsfiddle.net/futr8xv7/3/)

#### Steps to Reproduce
See jsfiddle.

#### Expected Results
- update latlng when dragging the marker.

#### Actual Results
- doesn't update latlng when dragging the marker.

### Browsers Affected

- [x ] Firefox

### Versions
- Leaflet: v1.0.3
- Vue: v2.5.16
- Vue2Leaflet: v1.1.1

**Comment by jkatagi** [comment]
Oh, I found that this is also happened without using Vuex store.
- woks at v1.0.2 : [new jsfiddle](https://jsfiddle.net/futr8xv7/5/)
- doesn't work at v1.11.1 : [new jsfiddle](https://jsfiddle.net/futr8xv7/4/)

**Comment by lordfuoco** [comment]
@jkatagi thank you for the issue, I will take a look!

**Comment by lordfuoco** [comment]
@jkatagi I see, before it was working due to the object being passed by reference.
There is a specific event and we need to listen to it, we will work on it soon :)

**Comment by lordfuoco** [comment]
@jkatagi  I am about to release a new version that includes a fix for this issue.
To avoid side effects you will need to add .sync modifier to lat-lng on the marker.
you can see the example 'some examples' to see it in action

**Comment by jkatagi** [comment]
@lordfuoco Thank you very much for you help! I'm waiting your release!

**Comment by lordfuoco** [comment]
@alexbainbridge yes it should be fixed as I see the events emitted on the vue panel, are you using .sync modifier ? Before there were side effects that are not nice

**Comment by alexbainbridge** [comment]
@lordfuoco Hi !
Yeah - using sync - it is changing, but not to the last dragged position. i.e. I drag a marker and the lat lng is set to a point during the drag rather than final position. 

Its the debounce that is the problem
https://github.com/alexbainbridge/Vue2Leaflet/commit/260a92900c0f188b3d49000409c198a2407004b9
I removed it and the last updated position is OK. 

Thinking outloud - would throttle work (rather than debounce?). Or could you leave throttling / debouncing to the parent code?

**Comment by lordfuoco** [comment]
@alexbainbridge Oh so is an error of the debounce function that I wrote, because it should be sent out with the latest value and not others! 
The debounce is needed because leaflet has a different precision and may trigger infinite loops, I will try to fix the error in the debounce fn! 

Thanks for the headsup

**Comment by alexbainbridge** [comment]
Sounds like you have this - but do you want me to open an issue? Or you reopen this one?

Thanks!

**Comment by lordfuoco** [comment]
@alexbainbridge we are not issue shy! Go on open it please, because I am swamped and I could forget if there is not an issue open :) thank you very much.

For the future, just go on and open an issue if you think there is a bug / mismatch / misalignment.
