### ISSUE TITLE
How to use leaflet-routing-machine in my vue2-leaflet maps?

### ISSUE THREAD

**Issue by aukhov** [KoRiGaN/Vue2Leaflet#292]
Hello.  Is the planning to develop plugin to [Leaflet Routing Machine](http://www.liedman.net/leaflet-routing-machine/) or something same routing plugin for leaflet?
And how can I use leaflet-routing-machine in my vue2-leaflet maps? How is possible to integrate these two modules?

**Comment by lordfuoco** [comment]
@aukhov Hi!.

We do not mantain plugins in the core repo but feel free to create one and submit a PR to add it to the plugin list!

In the meantime you can use `Leaflet routing machine` by putting a ref on the `l-map` component and retrieving the mapObject from there.

You can then use mapObject as follow:

```
L.Routing.control({
  waypoints: [
    L.latLng(57.74, 11.94),
    L.latLng(57.6792, 11.949)
  ]
}).addTo(mapObject);

```

Please check the documentation on how to safely use mapObject here:
https://korigan.github.io/Vue2Leaflet/#/quickstart?id=accessing-leaflet-api

**Comment by aukhov** [comment]
Thanks for feedback! mapObject works good. Waiting for new vue2-leaflet routing plugins =)

**Comment by carban** [comment]
Hello, I'm tying to work with vue2-leaflet and leaflet-routing-machine in my vue project, everything works well but when I refresh the page it returns me a blank page and in the Debugger of the web browser appears the error:
L.Routing = L.Routing || {};
I don't know what to do, it's confuse because on running time it works

I import the module on the script tag
`import Routing from 'leaflet-routing-machine';`

And then:
`  mounted() {
    this.$nextTick(() => {
      this.mapp = this.$refs.myMap.mapObject // work as expected
      L.Routing.control({
        waypoints: [
          [3.36803467132274, -76.5353965759277],
          [3.4194399148255, -76.4996910095215]
        ],
        routeWhileDragging: false
      }).addTo(this.mapp)
    })
  }`

**Comment by DonNicoJs** [comment]
Closing this

**Comment by b31zakx96** [comment]
please there is an error in the link documentation on how to safely use mapObject

**Comment by DonNicoJs** [comment]
@b31zakx96 This is the new docs link: https://vue2-leaflet.netlify.com/quickstart/#accessing-leaflet-api
