### ISSUE TITLE
Leaftlet providers and plugins

### ISSUE THREAD

**Issue by paparent** [KoRiGaN/Vue2Leaflet#363]
Hi ! 

I'd like to know how to use other providers and some plugins. For example I'd like to use the following :

https://github.com/leaflet-extras/leaflet-providers (to use HERE for example).

And bouncing from the following plugin :

https://github.com/hosuaby/Leaflet.SmoothMarkerBouncing

Thanks a lot !!

**Comment by DonNicoJs** [comment]
@paparent all the plugins that we are aware of are in the docs section if they are missing feel free to create one and make a PR to add them to our docs!

**Comment by paparent** [comment]
@DonNicoJs Hi

Yeah sure I can develop one ! But those two seemed a bit more complex (maybe, because I've never played with leaflet and vue-leaflet). So wanted input from other how easy is to implement that!

**Comment by DonNicoJs** [comment]
@paparent the best thing to do is to keep in consideration those points:

- leaflet exposes utility that you can leverage `findRealParent` and `propsBinder`
- everything should be initialised in the mounted lifecycle hook
- remember to set leaflet as a peerDependecy
- rollup is the best library bundler so you can leverage ESM ( you can check how we do it here in the main repo ) 
- if you want you can add me to the repo so I can keep an eye on the code, but I can't promise to be super fast because I am quite busy as it is :) 
- check this repo or one of the other plugins for inspiration ( for example leaflet-markercluster ) 


For the rest is easy to implement, a bit less easy to do it smoothly :) but I am here to help

**Comment by DonNicoJs** [comment]
Labelling as plugin-request and closing, feel free to re-open if you have more questions

**Comment by gelinger777** [comment]
any tutorial on creating a plugin?

**Comment by DonNicoJs** [comment]
@gelinger777 not that I am aware of, take a look at other plugins and take in consideration what I listed above

**Comment by gelinger777** [comment]
Any Ideas how to use this one? 

https://github.com/mapshakers/leaflet-mapkey-icon  ?

As I understood  would need to write a wrapper, for that, am I right?

**Comment by DonNicoJs** [comment]
@gelinger777 you don't need any plugin for this one, just import css and js and assign the icon to `LMarker`
