### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by Finrod927** [KoRiGaN/Vue2Leaflet#367]
Hi, and thanks for this great component.

But it's quite difficult to know what have changed between versions :
- NPM lists a 2.0.3 version, but the repository is still in 2.0.2
- There is no changelog file
- And no more detailed releases

Is it possible to have a Changelog file or detailled releases like it was done for 1.x versions?

Thanks :)

**Comment by DonNicoJs** [comment]
It is certainly possible! And It will happen. I am just very busy at the moment.

But: we follow semver. So 2.x changes are documented, 2.0.3 from 2.0.2 is a patch change that fixed a bug in the code.

It's probably here in GitHub because I forgot to push the change to package.json. 

I would love to have a more structured system to do releases. It's in the pipeline. 

If anyone want to stand up to help It would be appreciated. 

In the meantime you can be sure that I am going to jump immediately on every bug and tackle features / nice to have a bit more slowly

**Comment by DonNicoJs** [comment]
@Finrod927 I am planning to port the CI from travis to gitlab and use their CI / CD to do npm releases triggered from github versions/tag (as it was before the travis deploy broke)

**Comment by DonNicoJs** [comment]
@Finrod927 tags now are automatically synced when I do new npm version, and i am keeping up the changelog in the releases tab
