### ISSUE TITLE
Hello,Future plans with vue3.0?

### ISSUE THREAD

**Issue by infinityboy** [KoRiGaN/Vue2Leaflet#368]
#### Live Demo

http://jsfiddle.net/Boumi/k04zpLx9/

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: vX.X.X
- Vue: vX.X.X
- Vue2Leaflet: vX.X.X

**Comment by DonNicoJs** [comment]
@infinityboy 
if we can have a retro-compatible version: update as a minor version
if we can't have a retro-compatible version: release a new major and support 2x only for bug-fixes

But I believe we can have a retro-compatible version AND we can fix a lot of performance issue due to the new  Proxy-based Observation.

Is this what you wanted to know ?

**Comment by infinityboy** [comment]
Yes, thank you very much for your answer!
