### ISSUE TITLE
When v-bind:center changes it forces v-bind:zoom to restart

### ISSUE THREAD

**Issue by fergardi** [KoRiGaN/Vue2Leaflet#48]
When you bind the :center of the map to your vue data coordinates and you change it later (in order to pan the map, for example), the :zoom of the map also restarts to its original value, if it was changed.

This should be two separated processes.

**Comment by KoRiGaN** [comment]
Hi @fergardi,

For the moment only one way binding is supported. This means that if you change you values it will update the map but if you modify the map it will not update you values.

The only method in leaflet, as far as I know, to change center is to call setView that takes a center and a zoom. It currently use the value of the zoom you provide not the zoom the map is currently in.

I can think of 2 fix for this issue : 
- Make two way binding works on components. 
- Make the call to setView use the map zoom value instead of the zoom value provided.

**Comment by jteppinette** [comment]
@KoRiGaN could we support an event like "zoom:update" that pushes the new zoom level up to the parent. That would allow anyone that wanted to maintain parity to do so.

This is definitely a feature I am looking for.

**Comment by jteppinette** [comment]
So... right after I wrote that last comment, I remembered that most leaflet events actually are propogated up... and what do you know, this totally worked, thanks!

```
<v-map v-if="latlng && zoom" :zoom="zoom" :center="latlng" v-on:l-zoomend="({target: {_zoom: v}}) => zoom = v">
```

**Comment by KoRiGaN** [comment]
Hi @jteppinette,
Yes updating current zoom localy when a zoom event happen can also fix that issue.

**Comment by Grogglex** [comment]
Would this be related to the map re-centering when any data on the component changes? Like snapping back to the center value?

**Comment by KoRiGaN** [comment]
@fergardi, @jteppinette,

From v0.0.60 you can use .sync on the zoom value for it to be updated automatically from the map.

Hope this helps.

Micka

**Comment by KoRiGaN** [comment]
Closing as no comments for 3 weeks.
Please reopen this issue if it not solved yet.
