### ISSUE TITLE
load and viewreset events are not firing

### ISSUE THREAD

**Issue by dewdad** [KoRiGaN/Vue2Leaflet#51]
Out of the following events on the map component only zoomanim and moveend work.
I need to know when the map loads for the first time. Any suggestions?
```
<v-map :zoom=13 :center="[47.413220, -1.219482]" @l-zoomanim="mapReady" @l-viewreset="mapReady" @l-ready="mapReady" @l-load="mapReady" @l-moveend="mapReady">
</v-map>
...
mapReady(e){
      console.log(e)
}
```

**Comment by KoRiGaN** [comment]
Hi @dewdad ,
From my tests ready, moveend and zoomanim works correctly.

Not sure when viewreset is called in leaflet. It seems to have changed since v1 of leaflet and not be called anymore when user zoom/pan the map. See [this issue](https://github.com/Leaflet/Leaflet/issues/4837) 

The map load event will probably not work the way it is implemented today. Vue2Leaflet event are bound to leafelt Map once the map is created. Not sure how to fix this it would require more investigations.

In the meanwhile you can use the l-ready event. It should work.

Micka

**Comment by KoRiGaN** [comment]
Closed as no answer for 2 weeks
