### ISSUE TITLE
v-polyline opacity broken

### ISSUE THREAD

**Issue by brianmay** [KoRiGaN/Vue2Leaflet#73]
Hello,

Setting the `opacity` prop on a `v-polyline` has no effect. Looking at the `mounted` function, this prop (and others) are never used. Either the props should work, or they should be removed.

Furthermore, it would be ideal if `v-polyline` had an `options` prop like `v-marker`.

Oh, I see it has an `l-style` prop that can be used for the same purpose - this is confusing though having a very different name for the same purpose.

Regards

**Comment by KoRiGaN** [comment]
Hi @brianmay,
 
I agree having l-style / options is confusing, but I did it because of leaflet that have a method setStyle to set... options.

I have tested it and the opacity is broken unless you set it by the l-style property. 
```
:l-style="{opacity: 0.5 }"
```
I will fix soon the opacity (and other props that may not works as well) and let you know when this is available.

Cheers, 

Mickaël

**Comment by KoRiGaN** [comment]
Hi @brianmay,

Should be fixed in version 0.0.54.

Cheers,

Mickaël
