### ISSUE TITLE
Example are not working properly

### ISSUE THREAD

**Issue by RemiDesgrange** [KoRiGaN/Vue2Leaflet#74]
Hi,

I tried to launch the example of this repo, but it's no working:
node : 8.4  
npm: 5.4
ubuntu 16.04 on WSL.

step to reproduce :
```bash
git clone https://github.com/KoRiGaN/Vue2Leaflet.git
cd Vue2Leaflet
npm i
npm run dev
```
Error when `npm run dev`
``` 
 ERROR  Failed to compile with 15 errors                                                                        15:22:54

These dependencies were not found:

* vue2-leaflet in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/Simple.vue, ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/CustomUrlParams.vue and 10 others
* -!../node_modules/css-loader/index.js!../../node_modules/leaflet/dist/leaflet.css in ./~/css-loader!./~/vue-loader/lib/style-compiler?{"id":"data-v-82a029c4","scoped":false,"hasInlineConfig":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue

To install them, you can run: npm install --save vue2-leaflet -!../node_modules/css-loader/index.js!../../node_modules/leaflet/dist/leaflet.css


These relative modules were not found:

* ../../node_modules/leaflet/dist/images/marker-icon-2x.png in ./~/css-loader!./~/vue-loader/lib/style-compiler?{"id":"data-v-82a029c4","scoped":false,"hasInlineConfig":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue
* ../../node_modules/leaflet/dist/images/marker-shadow.png in ./~/css-loader!./~/vue-loader/lib/style-compiler?{"id":"data-v-82a029c4","scoped":false,"hasInlineConfig":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue
> Listening at http://localhost:8080
```

I know I can fix this localy but I think it could be great to have a working example out of the box  (right ?)

Thanks

**Comment by jteppinette** [comment]
Looks like you didn't run the link step.

**Comment by RemiDesgrange** [comment]
You're right, I followed the readme in the example folder, not the instruction in the main README, I'm closing this.

**Comment by tappoz** [comment]
Where does this `@import "~leaflet/dist/leaflet.css";` has to be included?

I've placed it inside the `<style> ... </style>` in either the main component `App.js` or a specific component, but I keep getting the same error message about leaflet CSS: `To install it, you can run: npm install --save -!../node_modules/css-loader/index.js?{"minimize":false,"sourceMap":false}!leaflet/dist/leaflet.css`

When removing the `@import "~leaflet/dist/leaflet.css";` from the  `<style> ... </style>` in the various places, then I can see some sort of map, but the image tiles are scattered all over the page in some sort of random way.

Also hard-coded paths from the `node_modules` directory don't seem to work (I've tested this using only `leaflet.js` separate from `Vue.js` though), but that's probably because webpack is bundling all together without exposing `node_modules`.
