### ISSUE TITLE
Updating options of a Marker component generates error when an icon property is not included

### ISSUE THREAD

**Issue by rayax86** [KoRiGaN/Vue2Leaflet#97]
### Description
Updating `options` of a Marker component generates error when an `icon` property is not included.

The reason is, in Marker.vue:
```
 mounted() {
    const options = this.options;
    if (this.icon) {
      options.icon = this.icon;
    }
    options.draggable = this.draggable;
    }
```

This segment of code should probably be ran every time the properties are updated e.g. using `computed` instead. That way updating options won't generate errors because no `icon` is provided.

#### Expected Results
Updating the `options` attribute of Marker does not generate error if no `icon` property is provided in the `options` object.

#### Actual Results
Updating the `options` attribute of a Marker component generates error if no `icon` property is provided in the `options` object.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11

### Versions
- Leaflet: v1.2.0
- Vue: v2.4.2
- Vue2Leaflet: v0.0.51

**Comment by KoRiGaN** [comment]
Could you test with Vue2Leaflet v0.0.57? PR #91 should already fix that issue.

Thanks,

Mickaël

**Comment by rayax86** [comment]
Hi @KoRiGaN, thanks for the advice, now it does not throw an error. :)
Yet, new options passed in still does not update the marker; I believe that's because in your `propsBinder` function:

```
   if (props[key].custom) {
      vueElement.$watch(key, (newVal, oldVal) => {
        vueElement[setMethodName](newVal, oldVal);
      }, {
        deep: deepValue
      });
    } else if (setMethodName == 'setOptions') {
      vueElement.$watch(key, (newVal, oldVal) => {

        L.setOptions(leafletElement, newVal);
      }, {
        deep: deepValue
      });
    }
```
The `else if` bit never get executed because `options` is a custom prop and only 
```
    setOptions(newVal) {
      Object.assign(this.options, newVal);
    },
```
is called which does not update the actual leaflet marker.

**Comment by KoRiGaN** [comment]
Hi @rayax86,

The problem you noticed is complex and related to Leaflet.
Options changes don't seem to have any impact on markers (I haven't investigated on other component but I think they have the same behaviour).

For example, you can initialise a marker with an opacity of 0.5 using options object and it will work:
```
{ opacity: 0.5 }
``` 
 But if you try to update it later to 1 in Leaflet like this, it will update the marker data but not the way the marker is displayed:
```
L.setOptions(marker, { opacity: 1 });  // doesn't work
marker.options.opacity = 1;  // doesn't work
``` 
The reason is that Leaflet has a dedicated method for that called setOpacity.
```
marker.setOpacity(1); // works
```
Internally leaflet is doing that:
```
marker.options.opacity = opacity;
if (marker._map) {
  marker._updateOpacity();
}
```
That could be a solution, but It will only work for some options (opacity, latLng) but not for others (title, draggable, etc).

My advice would be : 
- Use options properties if you just want to initialise a bunch of this that will never change.
- Use other properties (draggable for example) if you want something reactive.

Hope this helps,

Micka

**Comment by KoRiGaN** [comment]
Closing as no answer for a while
